"""Guardrails for SQL generated by a language model.

Enforced by a PARSER (sqlglot), not by the prompt — a prompt can be talked around,
a syntax tree cannot:
- exactly one statement (no "; DROP TABLE …"),
- SELECT only (also inside subqueries and CTEs),
- only whitelisted tables of the gold layer,
- an enforced LIMIT (no accidental dump of millions of rows).
Row access is additionally restricted by RLS/CLS in Unity Catalog (queries run with the
user's identity) — guardrails are a second, independent line of defence.
"""

from __future__ import annotations

import sqlglot
from sqlglot import exp

DEFAULT_ALLOWED_TABLES = frozenset(
    {
        "forecast_tomorrow",
        "backtest_metrics",
        "backtest_predictions",
        "reliability",
        "acceptance",
        "model_selection",
        "dq_summary",
    }
)
# Nodes that CHANGE something or execute commands — forbidden anywhere in the tree.
_FORBIDDEN = (
    exp.Insert, exp.Update, exp.Delete, exp.Drop, exp.Create, exp.Alter,
    exp.Merge, exp.Command, exp.Grant, exp.TruncateTable,
)


class UnsafeQueryError(ValueError):
    """Query rejected by the guardrails — the reason is shown to the user."""


def _table_name(t: exp.Table) -> str:
    """Table name for the whitelist check, plus a check that it belongs to gold.

    The catalog is ignored (the same SQL runs on smogcast_dev and smogcast_prod), but a
    schema, if present, MUST be ``gold`` — otherwise ``silver.forecast_tomorrow`` would
    pass on its name alone. Path tables (locally ``delta.`/…/gold/x```) are checked on
    the last two path elements.
    """
    name = t.name
    if "/" in name:
        parts = name.rstrip("/").split("/")
        if len(parts) < 2 or parts[-2].lower() != "gold":
            raise UnsafeQueryError(f"Only gold-layer tables are allowed: {name}")
        return parts[-1].lower()
    if t.db and t.db.lower() != "gold":
        raise UnsafeQueryError(f"Only gold-layer tables are allowed: {t.db}.{name}")
    return name.lower()


def validate_select(sql: str, allowed_tables: frozenset[str] = DEFAULT_ALLOWED_TABLES, max_limit: int = 1000) -> str:
    """Return a safe version of the query or raise ``UnsafeQueryError``."""
    try:
        statements = [s for s in sqlglot.parse(sql, read="databricks") if s is not None]
    except sqlglot.errors.ParseError as e:
        raise UnsafeQueryError(f"Invalid SQL syntax: {e}") from e
    if len(statements) != 1:
        raise UnsafeQueryError("Exactly one statement is allowed")
    stmt = statements[0]

    if not isinstance(stmt, (exp.Select, exp.Union, exp.Intersect, exp.Except)):
        raise UnsafeQueryError(f"Only SELECT is allowed (got {type(stmt).__name__})")
    for node in stmt.walk():
        if isinstance(node, _FORBIDDEN):
            raise UnsafeQueryError(f"Forbidden operation: {type(node).__name__}")

    cte_names = {c.alias_or_name.lower() for c in stmt.find_all(exp.CTE)}
    for t in stmt.find_all(exp.Table):
        name = _table_name(t)
        if name not in allowed_tables and name not in cte_names:
            raise UnsafeQueryError(f"Table not on the whitelist: {name}")

    limit = stmt.args.get("limit")
    if limit is None:
        stmt = stmt.limit(max_limit)
    else:
        try:
            value = int(limit.expression.name)
        except (AttributeError, ValueError):
            raise UnsafeQueryError("LIMIT must be a number") from None
        if value > max_limit:
            stmt = stmt.limit(max_limit)
    return stmt.sql(dialect="databricks")
